.github/workflows/cgl.yaml
.github/workflows/tests.yaml
README.md
composer.json
sonar-project.properties

Adds two new GitHub workflows:
* **CGL** contains jobs that test coding guidelines (composer.json normalization, linting, static code analysis)
* **Tests** contains jobs for Unit tests and Unit tests with lowest requirements
Additionally, Composer dev-requirements are fixed.

[TASK] Add GitHub workflows

---

Documentation/install.md
composer.json

This PR changes the projects' vendor name `fr` to `cpsit`. This is required since the vendor `fr` is already claimed by somebody else on Packagist.

[TASK] Change project vendor to "cpsit"

---

.github/workflows/tests.yaml
composer.json

This PR changes GitHub test workflow to use TYPO3 11.4 instead of 11.3.

[TASK] Add TYPO3 11.4 to GitHub test workflow

---

Classes/DataProcessing/AbstractDataProcessor.php

Since TYPO3 11.4 and https://forge.typo3.org/issues/94956 the use of the public property `$cObj` in data processors is deprecated. As a replacement, a public setter `setContentObjectRenderer` should be used. This commit adds this setter but keeps the public property as-is to assure compatibility with TYPO3 < 11.4.

[TASK] Add setter for $cObj in AbstractDataProcessor

---

Classes/DependencyInjection/HandlebarsHelperPass.php
Classes/Renderer/HandlebarsRenderer.php
Classes/Renderer/HelperAwareInterface.php
Classes/Traits/HandlebarsHelperTrait.php
Configuration/Services.yaml
Documentation/Usage/Extended/CustomRenderingComponents/Index.rst
Tests/Unit/Fixtures/Classes/Traits/DummyHandlebarsHelperTraitClass.php
Tests/Unit/Traits/HandlebarsHelperTraitTest.php

This PR introduces a new `HelperAwareInterface` that can be used to identify those Handlebars renderers that should be auto-configured by all globally registered Handlebars helpers. To achieve this goal, a new service tag `handlebars.renderer` has been introduced.

[!!!][FEATURE] Introduce autoconfiguration for Handlebars helpers at all Helper-aware renderers

---

Classes/Renderer/Template/HandlebarsTemplateResolver.php
Classes/Renderer/Template/TemplatePaths.php
Configuration/Services.yaml
Documentation/Configuration/TemplatePaths/Index.rst
Tests/Unit/Fixtures/Classes/DummyConfigurationManager.php
Tests/Unit/Fixtures/Classes/Renderer/Template/DummyTemplatePaths.php
Tests/Unit/HandlebarsTemplateResolverTrait.php
Tests/Unit/Renderer/Template/HandlebarsTemplateResolverTest.php
Tests/Unit/Renderer/Template/TemplatePathsTest.php

This PR introduces a new `TemplatePaths` class. It is used to merge configuration of template root paths and partial root paths from several configuration methods. Additionally, a new configuration method is introduced that allows definition of template root paths and partial root paths using TypoScript.
Example:
```typoscript
plugin.tx_handlebars {
view {
templateRootPaths {
10 = EXT:my_extension/Resources/Private/Templates
}
partialRootPaths {
10 = EXT:my_extension/Resources/Private/Partials
}
}
}
```
The new class `TemplatePaths` is now used within the `HandlebarsTemplateResolver` instead of passing an array of template root paths to it. This is a breaking change and should be considered when updating to the following new version of EXT:handlebars.

[!!!][FEATURE] Allow TypoScript as configuration for template paths

---

.github/workflows/release.yaml
.gitignore
Classes/Configuration/Extension.php
Documentation/Installation/Index.rst
Resources/Private/Libs/Build/composer.json
packaging_exclude.php

This PR introduces the possibility to install EXT:handlebars in non-composer (= classic) installations. For this, all relevant vendor-libraries are included as phar file in the generated ZIP file during TER publish.

[FEATURE] Add support for installs in non-composer mode

---

Classes/DataProcessing/AbstractDataProcessor.php
Documentation/Compatibility/ExtbaseRepositories.rst
Documentation/Compatibility/Index.rst
Tests/Unit/DataProcessing/AbstractDataProcessorTest.php
Tests/Unit/Fixtures/Classes/DataProcessing/DummyProcessor.php
Tests/Unit/Fixtures/Classes/DummyConfigurationManager.php

This PR provides a new compatibility method in `AbstractDataProcessor`. It can be used to reset the global `ConfigurationManager` that is responsible to e.g. resolve the storage PIDs defined in the current content element.
In order to use the new method, just call the `initializeConfigurationManager()` method in your data processor. **Note: This method is only available in case your data processor extends the `AbstractDataProcessor` class.**
```diff
namespace Vendor\Extension\DataProcessing;
use Fr\Typo3Handlebars\DataProcessing\AbstractDataProcessor;
class HeaderProcessor extends AbstractDataProcessor
{
protected function render(): string
{
+        $this->initializeConfigurationManager();
$data = $this->provider->get($this->cObj->data);
return $this->presenter->present($data);
}
}
```

[FEATURE] Provide compatibility method for Extbase repositories

---

Classes/DependencyInjection/HandlebarsHelperPass.php
Classes/Exception/InvalidHelperException.php
Classes/Traits/HandlebarsHelperTrait.php
Tests/Unit/Exception/InvalidHelperExceptionTest.php
Tests/Unit/Fixtures/Classes/Renderer/Helper/DummyHelper.php
Tests/Unit/Traits/HandlebarsHelperTraitTest.php

This PR adds full support for Handlebars helper functions in PHP 8 and higher.
Handlebars helper are normally registered using `Services.yaml` file or explicitly in the form `<class-name>::<method-name>`. In order to test whether the passed function for registering the helper is valid, a simple `is_callable` check was performed. PHP versions lower than 8.0 allowed to pass both static and non-static class methods in this form.
However, PHP 8.0 is more strict in various ways and no longer evaluates to `true` when passing non-static methods in the form `<class-name>::<method-name>` to `is_callable`. This leads to the fact that **all** helpers won't get registered when passed in with mentioned registration methods.
The validity check for passed Handlebars helpers is now defined in a way that …

[BUGFIX] Properly support helper functions in PHP 8 and higher

---

.github/workflows/release.yaml

This PR changes installation of `clue/phar-composer` from Composer to prebuilt phar file. This is necessary since the last release of this extension, dependencies for said package can no longer be resolved. This makes it unable to build and publish releases at TER.

[BUGFIX] Install clue/phar-composer from pre-built phar file

---

Tests/Unit/DependencyInjection/Extension/HandlebarsExtensionTest.php
composer.json

This PR adds a missing dependency to `typo3/cms-extbase` and updates dev-requirements.

[BUGFIX] Add missing dependencies and harden dev-requirements

---

Classes/Renderer/HandlebarsRenderer.php
Tests/Unit/Renderer/HandlebarsRendererTest.php

This PR changes the way how compile results are prepared for rendering.
Prior to this change, the compile results were written to `sys_get_temp_dir()` which is a bit spooky (since application-relevant files are no longer stored inside the application and depend on successful permission handling of those directories). Since TYPO3 already serves a temporary directory for such cases (`typo3temp/var/transient`), this one is now used to store compile results.
This drops the usage of the deprecated `LightnCandy\LightnCandy::prepare()` as well.

[FEATURE] Write compile result in `typo3temp` instead of `sys_get_temp_dir()`

---

Classes/DataProcessing/SimpleProcessor.php
Tests/Unit/DataProcessing/SimpleProcessorTest.php

Since TYPO3 11.4 and https://forge.typo3.org/issues/94956 the use of the public property `$cObj` in data processors is deprecated. As a replacement, a public setter `setContentObjectRenderer` should be used.
This PR adds this setter in `SimpleProcessor` but keeps the public property as-is to assure compatibility with TYPO3 < 11.4. This is a follow-up to #14.

[BUGFIX] Follow-up: Add setter for $cObj in SimpleProcessor as well

---

composer.json
phpstan-baseline.neon
phpstan.neon

Issue phpstan/phpstan#7020 was resolved with PHPStan 1.5.5. Therefore, this is now the minimum installable version of PHPStan.

[BUGFIX] Resolve PHPStan issue phpstan/phpstan#7020

---

Documentation/Contributing/Index.rst

The SonarCloud badge was already exchanged in cc7bc3679dfdecc2385a181b332fde8af30b27b7, but this was obviously forgotten in the documentation.

[DOCS] Use codecov badge in "Contributing" section

---

.github/workflows/cgl.yaml
.github/workflows/tests.yaml

This PR enables a workaround to avoid concurrent workflow runs. CGL and Tests workflows are now only run for `main` and `develop` branches when triggered via `push` event.

[BUGFIX] Avoid concurrent workflow runs in pull requests

---

Documentation/Compatibility/ExtbaseControllers.rst
Documentation/Compatibility/ExtbaseRepositories.rst
Documentation/Compatibility/Index.rst
Documentation/Configuration/Cache/Index.rst
Documentation/Configuration/Debugging/Index.rst
Documentation/Configuration/DefaultData/Index.rst
Documentation/Configuration/Index.rst
Documentation/Configuration/TemplatePaths/Index.rst
Documentation/Contributing/Index.rst
Documentation/Includes.rst.txt
Documentation/Index.rst
Documentation/Installation/Index.rst
Documentation/Introduction/Index.rst
Documentation/RenderingConcept/Index.rst
Documentation/Settings.cfg
Documentation/Sitemap.rst
Documentation/Usage/Basic/Index.rst
Documentation/Usage/Extended/CreateACustomHelper/Index.rst
Documentation/Usage/Extended/CustomRenderingComponents/Index.rst
Documentation/Usage/Extended/Events/Index.rst
Documentation/Usage/Extended/Index.rst
Documentation/Usage/Extended/SharedComponents/Index.rst
Documentation/Usage/Extended/SimpleProcessor/Index.rst
Documentation/Usage/Extended/UsingTheContentObjectRenderer/Index.rst
Documentation/Usage/Index.rst
Documentation/genindex.rst

This PR aligns the project documentation with the new documentation standard, see https://typo3.org/article/standardization-of-typo3-documentation-may-2022.

[DOCS] Align with new documentation standard

---

Classes/Data/Response/SimpleProviderResponse.php

Since the codebase still supports older PHP versions, we cannot fully reflect PHP 8.1 changes in method signatures and therefore add the `ReturnTypeWillChange` attribute.

[BUGFIX] Assure compatiblity with PHP 8.1 in SimpleProviderResponse

---

.github/workflows/tests.yaml

With this PR, the `ramsey/composer-install` action is now used to install Composer dependencies in the test workflow.

[TASK] Use ramsey/composer-install in test workflow

---

Documentation/Compatibility/ExtbaseControllers.rst
Documentation/Compatibility/ExtbaseRepositories.rst
Documentation/Compatibility/Index.rst
Documentation/Configuration/Cache/Index.rst
Documentation/Configuration/Debugging/Index.rst
Documentation/Configuration/DefaultData/Index.rst
Documentation/Configuration/Index.rst
Documentation/Configuration/TemplatePaths/Index.rst
Documentation/Contributing/Index.rst
Documentation/Includes.rst.txt
Documentation/Index.rst
Documentation/Installation/Index.rst
Documentation/Introduction/Index.rst
Documentation/RenderingConcept/Index.rst
Documentation/Sitemap.rst
Documentation/Usage/Basic/Index.rst
Documentation/Usage/Extended/CreateACustomHelper/Index.rst
Documentation/Usage/Extended/CustomRenderingComponents/Index.rst
Documentation/Usage/Extended/Events/Index.rst
Documentation/Usage/Extended/Index.rst
Documentation/Usage/Extended/SharedComponents/Index.rst
Documentation/Usage/Extended/SimpleProcessor/Index.rst
Documentation/Usage/Extended/UsingTheContentObjectRenderer/Index.rst
Documentation/Usage/Index.rst
Documentation/genindex.rst
docker-compose.yml

Indentation for `.rst` files is now streamlined to 4 spaces. This is now applied to the whole documentation.

[DOCS] Fix indentations in documentation

---

.gitattributes
packaging_exclude.php
phpstan-baseline.neon
phpstan.neon

We should rather maintain a baseline instead of adding ignored errors to the config file.

[TASK] Use PhpStan baseline for ignored errors

---

.github/dependabot.yml
Resources/Private/Libs/Build/composer.json
Resources/Private/Libs/Build/composer.lock

This PR enables Dependabot updates for libraries used for TER export (non-composer mode).

[TASK] Configure Dependabot for updates of non-composer mode libraries

---

.github/workflows/release.yaml

With GitHub [deprecating the `set-output` commands in GitHub workflows](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), the new `$GITHUB_OUTPUT` variable needs to be used instead.

[BUGFIX] Replace deprecated job outputs in GitHub workflows

---

Configuration/Services.php
rector.php

Some files such as `ext_localconf.php` must not have class imports, therefore we must skip the appropriate rule for Rector being applied on those files.

[BUGFIX] Skip Rector's class name import in some files

---

.gitattributes
.github/dependabot.yml
.github/workflows/cgl.yaml
.gitignore
composer.json
composer.lock

This PR adds a `composer.lock` file and enables Dependabot update for Composer dependencies, making CGL and test workflows more robust.

[TASK] Add `composer.lock` and enable Dependabot updates

---

.github/workflows/cgl.yaml
.github/workflows/release.yaml

The previously used action `softprops/action-gh-release` was not properly updated anymore. Thus, we now switch to the actively maintained action `ncipollo/release-action`.

[TASK] Switch to `ncipollo/release-action` for new releases

---

.github/workflows/release.yaml

With #78, the GitHub action for release generation was changed. However, the action output differs from the previously used action. This PR fixes access to the HTML url.

[BUGFIX] Fix access to HTML url of generated release

---

.github/dependabot.yml

Since TYPO3 extensions are considered libraries, we should not increase dependency versions in `composer.json` files. Instead, dependency ranges should be widened, avoiding incompatibilities in terms B/C.

[BUGFIX] Widen dependency versions via Dependabot

---

composer.json
composer.lock

This is required to keep PHP 7.4 support.

[BUGFIX] Allow installation of typo3/coding-standards 0.6.x

---

.github/workflows/tests.yaml
Documentation/Installation/Index.rst
composer.json
composer.lock

This PR adds support for PHP 8.2 (usable with TYPO3 11.5).

[FEATURE] Add support for PHP 8.2

---

.github/workflows/release.yaml

The @cpsitgmbh user may create releases in the future using our organization-wide release token :pray:

[TASK] Use release token in GitHub release job

---

Classes/Traits/ContentObjectRendererAwareTrait.php
Tests/Unit/Traits/ContentObjectRendererAwareTraitTest.php
composer.json
composer.lock

This PR improves type reflection in `ContentObjectRendererAwareTrait` when using `$this->assertContentObjectRendererIsAvailable()`. When using PHPStan >= 1.9.0 for static code analysis, `$this->contentObjectRenderer` is now treated as a valid instance of `ContentObjectRenderer` after the assertion method has been called successfully.

[BUGFIX] Reflect content object renderer type from assert method

---

Documentation/Compatibility/ExtbaseControllers.rst

The `type` property is required, but was forgotten in the code example. This is fixed now.

[DOCS] Add compatibility layer type to code example

---

.github/release.yml

We're currently in a project phase with only few substantial changes to the code base and a rather big amount of dependency maintenance commits by bots. With the current release template actual changes to the code base might not be that obvious to user in a sea of dependabot and renovate PRs.
That is why I'm proposing to change the order of PR categories (i.e. labels) in the release notes.

[TASK] Change order of categories in release notes

---

.github/workflows/cgl.yaml

`composer-unused` 0.8.7 was released, containing a fixed PHAR file.
This reverts commit de0155f9146982cf0a63cb2c381e02900b3eff8e.

[TASK] Revert "Use composer-unused 0.7 in CI"

---

composer.json
composer.lock
phpstan.neon

This PR requires and includes `phpstan/extension-installer`. In addition, superfluous config from `phpstan.neon` is removed.

[TASK] Use phpstan/extension-installer and clean up phpstan.neon

---

renovate.json

This PR changes the constraints in `renovate.json` to run updates with PHP 8.1.

[TASK] Run Renovate updates with PHP 8.1

---

renovate.json

This PR adds the correct Renovate PHP version constraint for `Resources/Private/Libs/Build/composer.json`.

[BUGFIX] Use proper Renovate constraints for libraries build dir

---

Classes/Exception/InvalidConfigurationException.php
Classes/Renderer/Helper/RenderHelper.php
Tests/Functional/Fixtures/test_extension/Classes/DefaultContextAwareConfigurationTrait.php
Tests/Functional/Fixtures/test_extension/Classes/DummyNonCacheableProcessor.php
Tests/Functional/Fixtures/test_extension/Classes/TemplatePathAwareConfigurationTrait.php
Tests/Functional/Renderer/Helper/RenderHelperTest.php

This PR adds a new `render` helper, inspired by the [JavaScript implementation within Fractal](https://github.com/frctl/fractal/blob/main/packages/handlebars/src/helpers/render.js).

[FEATURE] Introduce `render` helper

---

Classes/Renderer/Component/Layout/HandlebarsLayout.php
Classes/Renderer/Component/Layout/HandlebarsLayoutAction.php
Classes/Renderer/Helper/BlockHelper.php
Classes/Renderer/Helper/ContentHelper.php
Classes/Renderer/Helper/ExtendHelper.php
Tests/Functional/Fixtures/test_extension/Classes/JsonHelper.php
Tests/Functional/Fixtures/test_extension/Resources/Templates/main-layout-conditional-block.hbs
Tests/Functional/Fixtures/test_extension/Resources/Templates/main-layout-content-only.hbs
Tests/Functional/Fixtures/test_extension/Resources/Templates/main-layout-extended-with-conditional-contents.hbs
Tests/Functional/Fixtures/test_extension/Resources/Templates/main-layout-extended.hbs
Tests/Functional/Fixtures/test_extension/Resources/Templates/simple-layout-extended-with-context.hbs
Tests/Functional/Fixtures/test_extension/Resources/Templates/simple-layout-extended.hbs
Tests/Functional/Fixtures/test_extension/Resources/Templates/simple-layout.hbs
Tests/Functional/Renderer/Helper/ContentHelperTest.php
Tests/Functional/Renderer/Helper/ExtendHelperTest.php
composer.json
composer.lock

This PR adds the `block`, `content` and `extend` helpers, inspired by the appropriate [JS implementation from `handlebars_layouts`](https://github.com/shannonmoeller/handlebars-layouts).

[FEATURE] Introduce `block`, `content` and `extend` helpers

---

Classes/Attribute/AsHelper.php
Classes/Cache/HandlebarsCache.php
Classes/Compatibility/View/HandlebarsViewResolver.php
Classes/DataProcessing/SimpleProcessor.php
Classes/Renderer/HandlebarsRenderer.php
Classes/Renderer/Helper/BlockHelper.php
Classes/Renderer/Helper/ContentHelper.php
Classes/Renderer/Helper/ExtendHelper.php
Classes/Renderer/Helper/RenderHelper.php
Classes/Renderer/Helper/VarDumpHelper.php
Classes/Renderer/Template/TemplatePaths.php
Configuration/Services.php
Configuration/Services.yaml
Tests/Functional/Fixtures/test_extension/Classes/JsonHelper.php
Tests/Functional/Fixtures/test_extension/Configuration/Services.yaml
Tests/Unit/DependencyInjection/FeatureRegistrationPassTest.php

This PR introduces a new `#[AsHelper]` attribute. It can be used for auto-registration of Handlebars helpers. In addition, existing DI configuration is migrated to attributes where applicable.

[FEATURE] Introduce `#[AsHelper]` attribute for helper DI registration

---

Classes/Renderer/Component/Layout/HandlebarsLayout.php
Classes/Renderer/Component/Layout/HandlebarsLayoutAction.php
Classes/Renderer/Helper/BlockHelper.php
Classes/Renderer/Helper/ContentHelper.php
Classes/Renderer/Helper/Context/HelperContext.php
Classes/Renderer/Helper/Context/RenderingContextStack.php
Classes/Renderer/Helper/ExtendHelper.php
Classes/Renderer/Helper/HelperInterface.php
Classes/Renderer/Helper/RenderHelper.php
Classes/Renderer/Helper/VarDumpHelper.php
Classes/Traits/HandlebarsHelperTrait.php
Configuration/Services.php
Tests/Functional/Fixtures/test_extension/Classes/JsonHelper.php
Tests/Functional/Fixtures/test_extension/Resources/Templates/main-layout-extended-with-fifth-block.hbs
Tests/Functional/Fixtures/test_extension/Resources/Templates/main-layout-extended-with-fifth-content.hbs
Tests/Functional/Renderer/Helper/BlockHelperTest.php
Tests/Functional/Renderer/Helper/ExtendHelperTest.php
Tests/Functional/Renderer/Helper/RenderHelperTest.php
Tests/Unit/DataProcessing/SimpleProcessorTest.php
Tests/Unit/Fixtures/Classes/Renderer/Helper/DummyHelper.php
Tests/Unit/Renderer/Component/Layout/HandlebarsLayoutActionTest.php
Tests/Unit/Renderer/Component/Layout/HandlebarsLayoutTest.php
Tests/Unit/Renderer/HandlebarsRendererTest.php
Tests/Unit/Renderer/Helper/Context/HelperContextTest.php
Tests/Unit/Renderer/Helper/Context/RenderingContextStackTest.php
Tests/Unit/Renderer/Helper/VarDumpHelperTest.php
Tests/Unit/Traits/HandlebarsHelperTraitTest.php

This PR extends the existing `HelperInterface` by a new `render` method. The new method serves as official rendering entrypoint for custom helpers. It receives a `HelperContext` instance which is built around lightncandy's crazy array notation.

[!!!][FEATURE] Require `render` method with helper context in helpers

---

Classes/Renderer/Component/Layout/HandlebarsLayout.php
Classes/Renderer/Component/Layout/HandlebarsLayoutActionMode.php
Classes/Renderer/Helper/ContentHelper.php
Tests/Unit/Renderer/Component/Layout/HandlebarsLayoutActionTest.php
Tests/Unit/Renderer/Component/Layout/HandlebarsLayoutTest.php

This PR migrates the class constants `APPEND`, `PREPEND` and `REPLACE` in `HandlebarsLayoutAction` to an enum with appropriate cases. In addition, action names are now stored in the actions itself rather than in the consuming layout.

[!!!][FEATURE] Migrate handlebars layout action mode to enum

---

Classes/DependencyInjection/FeatureRegistrationPass.php
Classes/Renderer/Helper/BlockHelper.php
Classes/Renderer/Helper/ContentHelper.php
Classes/Renderer/Helper/ExtendHelper.php
Classes/Renderer/Helper/RenderHelper.php
Tests/Unit/DependencyInjection/FeatureRegistrationPassTest.php
Tests/Unit/Renderer/Helper/VarDumpHelperTest.php

Helpers shipped with EXT:handlebars should not be auto-registered, but instead respect extension configuration and use the provided feature registration pass to register each enabled helper.

[BUGFIX] Respect extension configuration for helper registration

---

Classes/DependencyInjection/Extension/Configuration.php
Classes/DependencyInjection/Extension/HandlebarsExtension.php
Configuration/Services.yaml
Documentation/Configuration/TemplatePaths/Index.rst
Tests/Unit/DependencyInjection/Extension/HandlebarsExtensionTest.php

This PR streamlines the view configuration of all template path providers by renaming the global root path configuration in service container from `template` to `view`:
```diff
handlebars:
default_data: []
-  template:
+  view:
templateRootPaths: []
partialRootPaths: []
```

[!!!][TASK] Streamline view configuration across path providers

---

Classes/DependencyInjection/Extension/Configuration.php
Classes/DependencyInjection/Extension/HandlebarsExtension.php
Classes/Event/BeforeRenderingEvent.php
Classes/Renderer/HandlebarsRenderer.php
Configuration/Services.yaml
Documentation/Configuration/Index.rst
Documentation/Configuration/Variables/Index.rst
Tests/Unit/DependencyInjection/Extension/HandlebarsExtensionTest.php
Tests/Unit/Event/BeforeRenderingEventTest.php
Tests/Unit/Renderer/HandlebarsRendererTest.php

This PR streamlines the naming of default data (also referenced as "root context") from `default_data` to `variables`, according to the naming used in Fluid context:
```diff
handlebars:
-  default_data:
+  variables:
foo: baz
view:
templateRootPaths: []
partialRootPaths: []
```

[!!!][TASK] Streamline root context with TYPO3 default naming

---

Classes/DependencyInjection/Extension/HandlebarsExtension.php
Classes/Renderer/HandlebarsRenderer.php
Classes/Renderer/Variables/GlobalVariableProvider.php
Classes/Renderer/Variables/TypoScriptVariableProvider.php
Classes/Renderer/Variables/VariableBag.php
Classes/Renderer/Variables/VariableProvider.php
Tests/Functional/Renderer/Helper/BlockHelperTest.php
Tests/Functional/Renderer/Helper/ContentHelperTest.php
Tests/Functional/Renderer/Helper/ExtendHelperTest.php
Tests/Functional/Renderer/Helper/RenderHelperTest.php
Tests/Unit/DataProcessing/AbstractDataProcessorTest.php
Tests/Unit/DataProcessing/SimpleProcessorTest.php
Tests/Unit/Renderer/HandlebarsRendererTest.php
Tests/Unit/Renderer/Template/Path/TypoScriptPathProviderTest.php
Tests/Unit/Renderer/Variables/GlobalVariableProviderTest.php
Tests/Unit/Renderer/Variables/TypoScriptVariableProviderTest.php
Tests/Unit/Renderer/Variables/VariableBagTest.php

This PR introduces a new `VariableProvider` component. It wraps the `variables` (previously `default_data`) section from service container which allows to provide default variables for use in each rendering. The new component is open for custom implementations. In addition, this PR adds support for definition of default variables using TypoScript (see `TypoScriptVariableProvider`). All variables from variables providers are merged together in the new `VariableBag` component which serves as entrypoint to fetch final default variables.

[!!!][FEATURE] Introduce `VariableProvider` for default variables

---

Classes/Renderer/Template/TemplatePaths.php
Tests/Unit/Renderer/Template/TemplatePathsTest.php

`PathProvider` instances are sorted by priority when passed as tagged iterator to `TemplatePaths`. Providers with higher priority are higher located than providers with lower priority. This was not properly reflected when iterating through providers, which is corrected by this PR.

[BUGFIX] Respect handling of path provider priority in `TemplatePaths`

---

Classes/Event/BeforeRenderingEvent.php
Tests/Unit/Event/BeforeRenderingEventTest.php

This PR extends the `BeforeRenderingEvent` to allow adding and removing a single variable using the `addVariable` and `removeVariable` methods.

[FEATURE] Allow modifying a single variable in `BeforeRenderingEvent`

---

Classes/Renderer/Template/Path/GlobalPathProvider.php
Classes/Renderer/Template/Path/PathProvider.php
Classes/Renderer/Template/Path/TypoScriptPathProvider.php
Classes/Renderer/Template/TemplatePaths.php
Tests/Unit/Fixtures/Classes/Renderer/Template/Path/DummyPathProvider.php
Tests/Unit/Renderer/Template/TemplatePathsTest.php

This PR extends the `PathProvider` interface by an `isCacheable` method. It describes the possibility of path providers to provide cached root paths. This information is used in `TemplatePaths` when building final root paths.

[FEATURE] Populate and read cacheable state of template path providers

---

Classes/Frontend/ContentObject/HandlebarsTemplateContentObject.php
Classes/Renderer/Template/BaseTemplateResolver.php
Classes/Renderer/Template/FlatTemplateResolver.php
Classes/Renderer/Template/HandlebarsTemplateResolver.php
Classes/Renderer/Template/Path/ContentObjectPathProvider.php
Configuration/Services.yaml
Tests/Functional/Fixtures/DummyRenderer.php
Tests/Functional/Frontend/ContentObject/HandlebarsTemplateContentObjectTest.php
Tests/Unit/Renderer/Template/Path/ContentObjectPathProviderTest.php

This PR introduces a new `HANDLEBARSTEMPLATE` content object. It accepts the following properties (like `FLUIDTEMPLATE`):
* `format`
* `templateName`
* `template`
* `file`
* `partialRootPath`
* `partialRootPaths`
* `templateRootPath`
* `templateRootPaths`
* `variables`
- including `data` and `current` as reserved variables
- allows simple hierarchy as well (`foo = bar` instead of `foo = TEXT` + `foo.value = bar`)
* `settings`
* `dataProcessing`
* `stdWrap`
In addition, the following properties are available:
* `headerAssets`
* `footerAssets`

[FEATURE] Introduce `HANDLEBARSTEMPLATE` content object

---

Classes/Renderer/Helper/BlockHelper.php
Classes/Renderer/Helper/ContentHelper.php
Classes/Renderer/Helper/Context/HelperContext.php
Classes/Renderer/Helper/ExtendHelper.php

The rendering context, which is applied to `HelperContext`, reflects `this` in Handlebars and can therefore be of any type. For example, when iterating over query results, it is an object of `AbstractEntity`. Thus, the underlying type is now widened to allow any kind of variable.

[BUGFIX] Allow any type of rendering context in HelperContext

---

Classes/Renderer/HandlebarsRenderer.php
Tests/Unit/Renderer/HandlebarsRendererTest.php

The rendering of HTML tags is actually quite useless, let's throw exceptions instead. 💥

[BUGFIX] Throw exceptions on errors and when debug is enabled

---

Classes/Frontend/ContentObject/HandlebarsTemplateContentObject.php
Tests/Functional/Frontend/ContentObject/HandlebarsTemplateContentObjectTest.php

This PR aims to improve the current situation with handling of both simple and complex variables in a `HANDLEBARSTEMPLATE` content object. This is a pre-patch for the introduction of a new Extbase-related Handlebars view.

[FEATURE] Improve processing of simple and complex cObj variables

---

Classes/Extbase/View/ExtbaseHandlebarsView.php
Classes/Extbase/View/ExtbaseHandlebarsViewResolver.php
Configuration/Services.yaml
Tests/Unit/Extbase/View/ExtbaseHandlebarsViewResolverTest.php
Tests/Unit/Extbase/View/ExtbaseHandlebarsViewTest.php
composer.json
composer.lock

This PR introduces an `ExtbaseHandlebarsView` along with an `ExtbaseHandlebarsViewResolver`. Both are used for Extbase controllers to render a Handlebars template instead of a Fluid template.
For third-party controllers, Handlebars template rendering can be enabled by adding a dedicated TypoScript configuration to the plugin. Example:
```
plugin.tx_news {
handlebars {
templateName = CASE
templateName {
key.field = controllerNameAndAction
News::list = TEXT
News::list.value = @news-list
default = @news
}
}
}
```
This renders the `news-list` Handlebars template for the News list action, all other actions will be rendered with the generic `news` Handlebars template.
If no `templateName` can be resolved (i.e., no `default` is given in the `CASE` cObj), the default view resolver is used (that …

[FEATURE] Introduce Handlebars view for Extbase context

---

Classes/Extbase/View/ExtbaseHandlebarsViewResolver.php
Tests/Unit/Extbase/View/ExtbaseHandlebarsViewResolverTest.php

With this PR, the template format is now properly respected in `ExtbaseHandlebarsViewResolver`. The default value is `hbs`. It can be overridden using TypoScript.

[BUGFIX] Respect template format passed to ExtbaseHandlebarsViewResolver

---

Classes/Renderer/Helper/Context/HelperContext.php

Use `array_key_exists` instead of the type-unsafe `isset`.

[BUGFIX] Harden check for array offset in HelperContext

---

Classes/Frontend/ContentObject/HandlebarsTemplateContentObject.php
Tests/Functional/Frontend/ContentObject/HandlebarsTemplateContentObjectTest.php

The `headerAssets` and `footerAssets` configuration options are now parsed as content objects instead of a single `HANDLEBARSTEMPLATE` content object.
Example:
```
headerAssets = COA
headerAssets {
10 = HANDLEBARSTEMPLATE
10.templateName = @meta-head
}
```

[FEATURE] Render `headerAssets` and `footerAssets` as content object

---

Classes/Cache/HandlebarsCache.php
Classes/DependencyInjection/FeatureRegistrationPass.php
Classes/Frontend/ContentObject/HandlebarsTemplateContentObject.php
Classes/Renderer/HandlebarsRenderer.php
Classes/Renderer/Template/FlatTemplateResolver.php
Configuration/Services.yaml
Tests/Unit/DependencyInjection/FeatureRegistrationPassTest.php
ext_conf_template.txt

Remaining configuration in `Services.yaml` is now migrated to attributes. In addition, the `FlatTemplateResolver` is now the default template resolver, since it is also compatible with (?= falls back to) `HandlebarsTemplateResolver`.

[!!!][TASK] Migrate service configuration to attributes

---

Classes/Renderer/Template/BaseTemplateResolver.php
composer.json
composer.lock

When resolving template paths via `TemplateResolver`, absolute paths can now be resolved as well.

[FEATURE] Support absolute template paths in template resolvers

---

Classes/Frontend/ContentObject/HandlebarsTemplateContentObject.php
Tests/Functional/Frontend/ContentObject/HandlebarsTemplateContentObjectTest.php

A new content object configuration option `unflattenVariableNames` is introduced. It can be used to unflatten variables like `foo.baz.boo` to its multidimensional array representation.
TypoScript:
```
lib.foo = HANDLEBARSTEMPLATE
lib.foo {
dataProcessing {
10 = menu
10 {
as = foo.baz.boo
}
}
unflattenVariableNames = 1
}
```
Resulting variables:
```
foo {
baz {
boo = # Processed menu variables
}
}
```

[FEATURE] Introduce possibility to unflatten variable names
